# Introduction to Materials Science

For students who completed their undergraduate studies in fields other than Materials Science and Engineering (MSE), we recommend a thorough review of one or more introductory texts. This review will provide exposure to concepts that may not have been previously encountered, and allowing for more advanced study within the MSE core. The references below are recommended introductory, undergraduate-level (200- or 300-level) texts. A limited number of these texts are available through the Northwestern Engineering Library, but students may find that their advisors and lab-mates may have extra copies on-hand.

We have deposited some of these texts onto the department's electronic reserve, hosted [here](https://northwestern.box.com/s/13myp0an8snmmfjqfbx9gt1gbfrah0aj), or find it on the Materials Science Canvas site under `\Files\eReserve`.

1.  **Principles of Electronic Materials and Devices, Ed. 3, Ch. 1 *Safa O. Kasap*, McGraw Hill, 2006**:

    **Resource:** Ch. 1 of Kasap is available on the [eReserve](https://northwestern.box.com/s/13myp0an8snmmfjqfbx9gt1gbfrah0aj).

    Principles of Electronic Materials and Devices is a text used in Northwestern's undergraduate Physics of Materials courses (MAT`_`SCI 351-1). While focusing on electronic structure and properties, Kasap spends the first 100 pages providing a broad, conceptual review of important topics in Materials Science and Engineering. This is the minimum suggested reading for those with no background in MSE and is provided in the eReserve.

    **Suggested Reading:**

    Kasap touches briefly on many introductory MSE core topics. A read through this material will provide familiarity with concepts that will arise in the MAT`_`SCI graduate core. Courses in which you will encounter these topics are listed in parentheses.

    1.  Pgs. 9-25: Bonding and Materials Classification (401, 404, 405, 406, 408).

    2.  Pgs. 25-36: Kinetic Molecular Theory (401, 408).

    3.  Pgs. 40-45: Heat and Thermal Fluctuations (401, 404, 405, 408).

    4.  Pgs. 45-49: Thermally Activated Processes (401, 404, 405, 406, 408).

    5.  Pgs. 49-63: Crystal Structures (404, 405, 406, 408)

    6.  Pgs. 64-76: Crystalline Defects (404, 406, 408).

    7.  Pgs. 78-82: Glasses and Amorphous Materials (401, 408).

    8.  Pgs. 78-82: Glasses and Amorphous Materials (401, 408).

    9.  Pgs. 83-94: Solid Solutions and Two-Phase Solids (401, 408)

2.  **Phase Transformations in Metals and Alloys, Ed. 3, Ch. 1 *Porter, Easterling, and Sherif*, Chapman and Hall, 2008**

    **Resource:** Ch. 1 of Porter and Easterling is available in the [eReserves](https://northwestern.box.com/s/13myp0an8snmmfjqfbx9gt1gbfrah0aj).

    Porting and Easterling is an text introducing phase transformations for 3^rd^ and 4^th^ year undergraduates. Ch. 1 provides background information on thermodynamical principles central to MAT`_`SCI 401 and 408. Some of the material in Ch. 1 is covered in MAT`_`SCI 401, but students should be familiar with these concepts prior to enrollment in MAT`_`SCI 408.

3.  **Materials Science and Engineering, an Introduction, Ed. 9e, *William D. Callister, Jr. and David G. Rethwisch*, Wiley, 2014**:

    This text is often used in the Northwestern Materials Science undergraduate introduction course, taken in the 2^nd^ year. Callister provides a basic introduction to core materials science concepts associated with structure, properties, processing, and performance. It is very detailed and not suggested as the best text for someone completely unfamiliar with MSE concepts. The text has a more specific focus on the details of metals processing than many introductory texts.

    **Suggested Reading:**

    A list of the core topics covered in an introductory MSE core course are listed below. The MAT`_`SCI graduate core courses in which you will encounter these topics are listed in parentheses.

    1.  Ch. 2: Electronic structure and inter-atomic pair potentials (405).

    2.  Ch. 3: Basic metallic crystalline structures and crystal navigation (404, 405, 406, 408).

    3.  Ch. 4: Imperfections. Simple 0D, 1D, 2D and 3D defects in materials (404, 406, 408).

    4.  Ch. 5: Diffusion. 1D formulations of Fick's 1^st^ and 2^nd^ Laws (401, 404, 408).

    5.  Ch. 6, 7, 8: Microstructural mechanical response: Elasticity, plasticity, and failure (404, 406).

    6.  Ch. 9: Phase Diagrams: Simple phase diagram interpretation and the Gibbs Phase Rule (401, 408).

    7.  Ch. 10: Kinetics in phase transformations and the equilibrium state (401, 408).

    **Resource:** There is no copy of this book in the MAT`_`SCI eReserves. However, there are dozens of copies floating around the department. Ask your lab-mates or your advisors for a copy.

4.  **Introduction to Materials Science for Engineers, Ed. 8, *James F. Shackelford*, Pearson, 2015**:

    Shackelford's book is similar to that of Callister's, but the content is more selective. This book is also more concise and takes a more conceptual approach to MSE than Callister. The problems are often composed to provide engineering context. Shackelford spends much less time on processing than Callister, but covers structure, properties and performance at the same level of detail.

    **Resource:** There is no copy of this book in the MAT`_`SCI eReserves. However, there are many copies floating around the department. Ask your lab-mates or advisors for a copy.
