---
title: "Northwestern University Materials Science and Engineering Graduate Core Coursepack"
author: "Jonathan D. Emery and Lincoln J. Lauhon"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
classoption: openany
bibliography: coursepack.bib
biblio-style: apalike
link-citations: yes
output:
  bookdown::gitbook: 
    includes:
      in_header: mathjax.html
  bookdown::pdf_book:
    latex_engine: xelatex
    template: graduate-coursepack.tex
---

# Abstract {-}

This coursepack is intended to serve matriculating graduate students as a resource for the foun-dational knowledge necessary to succeed in the Materials Science and Engineering Department’sgraduate core curriculum. Students should review this coursepack prior to and during their en-rollment. This coursepack contains references and original material with focus on MaterialsScience and Engineering background, mathematics, and coding.

## Disclaimer {-}

The coursepack is intended to be an evergreen document. Improvements, corrections, and updates will be completed with feedback from graduate students and core instructors. Tentative release dates for new material are noted in section headings.

Students and instructors are invited to comment directly on the PDF or to contact Jonathan Emery at <jonathan.emery@northwestern.edu> with suggestions.

## Intended Outcomes {-}

Students that study this coursepack and referenced documents should be able to:

1.  Demonstrate familiarity with foundational undergraduate-level Materials Science concepts as covered in Chapter 1 of Kasap[@kasap2006principles].

2.  Navigate constitutive relations using tensor notation and operations.

3.  Employ various techniques --- such as separation of variables and Fourier analysis --- to solve introductory boundary value problems (e.g. diffusion, heat transfer, linear elasticity).

4.  Construct rudimentary MATLAB or Mathematica scripts to solve problems and visualize/analyze data.

## Multimedia Content {-}

This document contains multimedia content including video and imbedded interactive 3D graphics. This content is supported through Adobe products (e.g. Adobe Acrobat Reader DC), but the reader must approve the use of multimedia content in Adobe. This can be done when opening the document for the first time: `Allow Multimedia Content` or by navigating to `Edit` $\rightarrow$ `Preferences` $\rightarrow$ `Multimedia Trust`: `Allow Multimedia Operations`.

Interaction with multimedia is done directly within the PDF. Click on content to play short videos or animations. Click-and-twist to rotate 3D interactive content such as crystal structures.

## Northwestern Materials Science and Engineering eReserves {-}

The department has made available portions of select introductory texts suitable for students who have limited background in materials science. These texts are stored in an online repository hosted on Northwestern box, and are available to all Northwestern Materials Science students [here](https://northwestern.box.com/s/13myp0an8snmmfjqfbx9gt1gbfrah0aj). Brief descriptions of these texts are available in [the intro](#introduction-to-materials-science).

By utilizing these texts, you are agreeing to [Northwestern's policies on eReserve](is not to be used for any purpose other than private study, scholarship, or research. If electronic transmission of reserve material is used for purposes in excess of what constitutes ``fair use'', that user may be liable for copyright infringement.), which are compliant with US copyright law (Title 17, United States Code):

::: displayquote
$\left[\text{Sources are}\right]$ not to be used for any purpose other than private study, scholarship, or research. If electronic transmission of reserve material is used for purposes in excess of what constitutes "fair use," that user may be liable for copyright infringement.
:::


```{r, echo=FALSE}
file.copy('siunitx.js', '_book/siunitx.js')
```
